Use the .get method instead
Checking for environment variables using os.environ['EnvVarName'] will fail if the environment variable does not exist.  The .get method will return None if the key doesn't exist, which gives the desired result.
```
Traceback (most recent call last):
  File "/start.py", line 11, in <module>
    if not os.environ["SOCKET_PORT"]:
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SOCKET_PORT'
```